spring.application.name=spring-ai

#spring.ai.openai.base-url=api.openai.com
#spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.vertex.ai.gemini.project-id=${PROJECT_ID}
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash
spring.ai.vertex.ai.gemini.chat.options.temperature=0.5
