spring.application.name=spring-ai

# Chat Open AI
#spring.ai.openai.base-url=api.openai.com
#spring.ai.openai.api-key=${OPENAI_API_KEY}

# Chat Gemini Google
#spring.ai.vertex.ai.gemini.project-id=${PROJECT_ID}
#spring.ai.vertex.ai.gemini.location=us-central1
#spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash
#spring.ai.vertex.ai.gemini.chat.options.temperature=0.5

# Chat Azure Microsoft
	# Create Account Microsoft Azure e Configure Azure OpenAI para Acesso
spring.ai.azure.openai.api-key=${AZURE_OPENAI_API_KEY}
spring.ai.azure.openai.endpoint=${AZURE_ENDPOINT}
	# Create Model Deployment no Azure AI Foundry
spring.ai.azure.openai.chat.options.deployment-name=gpt-4o-mini
